version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: videodb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/usr/share/nginx/html/hls:ro
    ports:
      - "8080:80"
    restart: unless-stopped
  

  worker:
    build:
      context: ../app/worker
      dockerfile: dockerfile.worker
    env_file:
      - ../app/worker/.env
    volumes:
      - ./data/worker_tmp:/tmp   # mount host folder as /tmp inside container
    depends_on:
      - redis
      - minio
      - postgres
