events {}

http {
  server {
    listen 80;

    # Web frontend
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://web:3000;
    }

    # NextAuth routes (catch-all)
    location ~ ^/api/auth/(?!sync).*{
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://web:3000;
    }

    # All other API routes go to API container
    location /api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://api:4000/;
    }

    # HLS -> proxy to MinIO (bucket videos)
    location /hls/ {
      proxy_set_header Host $host;
      proxy_pass http://minio:9000/videos/hls/;
      proxy_hide_header Access-Control-Allow-Origin;
      add_header Access-Control-Allow-Origin * always;
      add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
      add_header Access-Control-Allow-Headers '*' always;
      types {
        application/vnd.apple.mpegurl m3u8;
        application/x-mpegURL m3u8;
        video/mp2t ts;
        image/jpeg jpg;
        image/png png;
      }
    }
  }
}
