events {}

http {
  server {
    listen 80;

    # Web frontend
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://web:3000;
    }

    # NextAuth routes (catch-all)
    location ~ ^/api/auth/(?!sync).*{
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://web:3000;
    }

    # All other API routes go to API container
    location /api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://api:4000/;
    }

location /videos/ {
    proxy_pass http://minio:9000/videos/;
    proxy_set_header Host minio:9000;
    proxy_set_header Cookie "";
    client_max_body_size 500m;
    proxy_buffering off;
    proxy_request_buffering off;
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, PUT, POST, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "*" always;

    if ($request_method = OPTIONS) {
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
    }
}

    # HLS -> proxy to MinIO (bucket videos)
    location /hls/ {
      proxy_set_header Host $host;
      proxy_pass http://minio:9000/videos/hls/;
      proxy_hide_header Access-Control-Allow-Origin;
      add_header Access-Control-Allow-Origin * always;
      add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
      add_header Access-Control-Allow-Headers '*' always;
      types {
        application/vnd.apple.mpegurl m3u8;
        application/x-mpegURL m3u8;
        video/mp2t ts;
        image/jpeg jpg;
        image/png png;
      }
    }
  }
}
